### ISSUE TITLE
Criar os arquivos `de alicerce` que formarão a estrutura base do projeto

### ISSUE THREAD

**Issue by theandersonn** [tnn-mentoring/jusa-lawyer-html-2#3]
Antes de realizar esses passos, não esqueça:
1. mova-se para a branch `main` **(git checkout main)**
2. baixe as modificacoes que o repositorio recebeu **(git pull origin main)**
3. crie uma nova branch para trabalhar **(git checkout -b FEAT-3)**

## Dentro da pasta `sass` crie a pasta `base` com os arquivos:

_fonts.scss
```css
@import url('https://fonts.googleapis.com/css2?family=Mulish:wght@400;700&family=Playfair+Display&display=swap;family=Roboto&display=swap');
```

_reset.scss
```css
:root {
  --color-primary: #1E2027;
  --color-secondary: #DFAE4F;
  --color-darkGray: #666D79;
  --color-ashGray: #C7C3B3;
  --color-lightGray: #F0EEE9;
  --color-white: #FFFFFF;
  --fontM: 'Mulish', sans-serif;
  --fontP: 'Playfair Display', serif;
  --fontR: 'Roboto', sans-serif;
  --gap-page: 1.5rem;
  --height-logo: 4.2rem;
  --height-header: 10.2rem;
  --line-minor: 6rem;
  --margin-description-top: 2.4rem;
  --margin-font-top: 3.2rem;
  --margin-button-top: 3.2rem;
  --margin-page: 1.5rem;
  --margin-page-top: 6.4rem;
  --margin-photo-top: 4.8rem;
  --time-transition: 400ms;

  @media (min-width: 767px) {
    --line-minor: 12rem;
  }

  @media (min-width: 992px) {
    --margin-page-top: 18rem;
    --margin-page: 13.5rem;
  }
}

* {
  -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
          box-sizing: border-box;
  margin: 0;
  padding: 0;
}

body::-webkit-scrollbar {
  width: 0;
  height: 0;
}

fieldset {
  border: none;
  border-top: 0.2rem solid var(--color-secondary);
}

legend {
  font-size: 2rem;
  line-height: 1;
  margin-left: var(--line-minor);
  min-width: -webkit-fill-available;
  min-width: -moz-fill-available;
  min-width: -o-fill-available;
  padding-left: 1rem;
}

button {
  border: none;
  font-size: 1.8rem;
  height: 8rem;
  margin-top: var(--margin-button-top);
  min-width: 20rem;
  width: 100%;

  @media (min-width: 767px) {
    width: 20rem;
  }
}

```

_reset.scss
```css
html {
  font-size: 62.5%;
}

body {
  background: #E5E5E5;
  font-size: 1.6rem;
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;

  font-family: var(--fontM);
  font-weight: normal;

  color: var(--color-white);
  list-style: none;
  text-decoration: none;
}

a {font-size: 1.4rem;}
h1 {font-size: 3.6rem;}
h2 {font-size: 2.8rem;}
h3 {font-size: 2.2rem;}
h4 {font-size: 2.0rem;}
h5 {font-size: 1.8rem;}
h6 {font-size: 1.4rem;}

@media (min-width: 1200px) {
  h1 {font-size: 6.4rem;}
  h2.title {font-size: 4.6rem;}
}

```

## Dentro da pasta `sass` crie a pasta `general` com os arquivos:

_buttons.scss
```css
.buttons {
  @media (min-width: 767px) {
    display: flex;
    gap: var(--margin-button-top);
  }
}

.button-orange {
  background-color: var(--color-secondary);
}

.button-black {
  background-color: transparent;
  border: solid 0.1rem var(--color-white);
}
```

_container.scss
```css
  .container section[id='*'] {
    @media (min-width: 992px) {
      padding: var(--margin-page-top) var(--margin-page);
    }
  }

```

_description.scss
```css
.description {
  padding-top: var(--margin-description-top);
}
```

_title.scss
```css
.title {font-family: var(--fontP);
  padding-top: var(--margin-font-top);
}
```

## No arquivo `main.scss` que foi criado anteriormente insira o conteúdo:

```css
/* base */
@import "base/fonts";
@import "base/reset";
@import "base/typography";

/* general */
@import "general/container";
@import "general/buttons";
@import "general/description";
@import "general/title";
```

Rode o comando e veja seja está funcionando, gerando em `static/css` o `style.css`
```bash
yarn compile:sass
```
